Fix GCC warnings and linker error for ATF builds
Add (void) casts, __attribute__((unused)), and stub functions to
suppress compiler warnings when debug macros are disabled, and fix
a linker error when SILENT_LIB is defined.

Fixes the following compilation errors with -Werror:

ddr3_training_centralization.c: In function 'ddr3_tip_centralization':
  ddr3_training_centralization.c:161:57: error: variable 'end_window_skew' set but not used [-Werror=unused-but-set-variable]
  ddr3_training_centralization.c:161:38: error: variable 'start_window_skew' set but not used [-Werror=unused-but-set-variable]
  ddr3_training_centralization.c:161:24: error: variable 'waste_window' set but not used [-Werror=unused-but-set-variable]

ddr3_training_leveling.c: In function 'mv_ddr_rl_dqs_burst':
  ddr3_training_leveling.c:1830:24: error: variable 'max_phase' set but not used [-Werror=unused-but-set-variable]
  ddr3_training_leveling.c:1830:13: error: variable 'min_phase' set but not used [-Werror=unused-but-set-variable]
  ddr3_training_leveling.c:1825:30: error: variable 'final_rd_ready' set but not used [-Werror=unused-but-set-variable]
  ddr3_training_leveling.c:1825:13: error: variable 'final_rd_sample' set but not used [-Werror=unused-but-set-variable]

mv_ddr4_training_calibration.c: In function 'mv_ddr4_centralization':
  mv_ddr4_training_calibration.c:444:49: error: variable 'end_win_skew' set but not used [-Werror=unused-but-set-variable]
  mv_ddr4_training_calibration.c:444:33: error: variable 'start_win_skew' set but not used [-Werror=unused-but-set-variable]
  mv_ddr4_training_calibration.c:444:22: error: variable 'waste_win' set but not used [-Werror=unused-but-set-variable]

mv_ddr4_training_calibration.c: In function 'mv_ddr4_center_of_mass_calc':
  mv_ddr4_training_calibration.c:1050:37: error: variable 'slope' set but not used [-Werror=unused-but-set-variable]

mv_ddr4_training_calibration.c: At top level:
  mv_ddr4_training_calibration.c:130:20: error: 'str_dir' defined but not used [-Werror=unused-variable]

Linker error (undefined reference to mv_ddr_user_log_level_set):
  ATF builds could pass -DSILENT_LIB which excluded mv_ddr_user_log_level_set
  from compilation, but ddr3_init.c still called it. Added stub function
  in the SILENT_LIB case.